version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otj_password
      MYSQL_DATABASE: 'otj'
    ports:
      - '3306:3306'
    volumes:
        - ./sql/create.sql:/docker-entrypoint-initdb.d/1_create.sql
        - ./sql/insert.sql:/docker-entrypoint-initdb.d/2_insert.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080